#!/bin/bash

# When prioritising night activity on fauna cameras, the hour before sunset
# and the hour after sunrise are important to include

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 photos.csv times.csv"
    exit 1
fi

photos_file="$1"
times_file="$2"

if [ ! -f "$photos_file" ] || [ ! -f "$times_file" ]; then
    echo "Input files not found."
    exit 1
fi

declare -A sunrise_times
declare -A sunset_times

while IFS=, read -r date sunrise sunset; do
    # add 1 hour to sunrise and store as a number
    sunrise_times["$date"]=$(echo "$sunrise" | awk -F':' '{printf "%02d%02d%02d\n", $1+1, $2, $3}')

    # convert to 24hr time and subtract 1 hour from sunset and store as a number
    sunset_times["$date"]=$(echo "$sunset" | awk -F':' '{printf "%02d%02d%02d\n", $1+11, $2, $3}')
done <"$times_file"

while IFS=, read -r file timestamp; do
    date=$(echo "$timestamp" | cut -d " " -f1)
    dawn=${sunrise_times[$date]}
    dusk=${sunset_times[$date]}

    # convert the 24hr time into a 6 digit number for fast comparison
    # creating date objects and unixtimestamps is too slow over millions of photos
    time_num=$(echo "$timestamp" | cut -d " " -f2 | tr -d ":")

    if ! [[ $time_num =~ ^[0-9]+$ && $dawn =~ ^[0-9]+$ && $dusk =~ ^[0-9]+$ ]]; then
        echo "Bad time data. Time:$time_num dawn:$dawn dusk:$dusk" >&2
    else
        # Check if the timestamp is between 00:00:00 and dawn, or between dusk and 23:59:59
        if [ "$time_num" -lt "$dawn" ] || [ "$time_num" -gt "$dusk" ]; then
            echo "$file"
        fi
    fi
done <"$photos_file"
