#!/bin/bash

# Default values
target=""

if ! command -v exif >/dev/null; then
    echo "Error: exif is not installed. Please install it and try again."
    exit 1
fi

usage() {
    echo "Usage: $0 <target_directory>"
}

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
    --help)
        usage
        exit 0
        ;;
    *)
        target="$1"
        ;;
    esac
    shift
done

if [ -z "$target" ]; then
    usage
    exit 1
fi

find "$target" -iname '*.jpg' | while IFS= read -r file; do
    # Extract the date from the exif timestamp and format as YYYY-MM-DD HH:mm:SS instead of the YYYY:MM:DD HH:mm:SS format recorded on Swift cameras
    date=$(
        exif -m -t=DateTimeOriginal "$file" |
            sed 's/\([0-9]\{4\}\):\([0-9]\{2\}\):\([0-9]\{2\}\) \(.*\)/\1-\2-\3 \4/'
    )
    if [ -n "$date" ]; then
        echo "$file,$date"
    else
        echo "Timestamp missing or invalid: $file,$date" >&2
    fi
done
